# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-08 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=100)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Unknown')], default='U', help_text='Report response', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.user'),
        ),
    ]
